export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK'
export const PAUSE = 'PAUSE'
export const NEXT_TRACK = 'NEXT_TRACK'
export const PREV_TRACK = 'PREV_TRACK'
