export const playlistMusic = [
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Guilt',
    soName: '',
    author: 'Nero',
    album: 'Welcome Reality',
    duration_in_seconds: 3728,
    year: '1980',
    genre: 'rock',
    id: 'fghtfgkhmjrtlkhnfgb',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Elektro',
    soName: '',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    duration_in_seconds: 1420,
    year: '2020',
    genre: 'rock',
    id: '45645fdgklerjt54j',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'I’m Fire',
    soName: '',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    duration_in_seconds: 143,
    year: '2001',
    genre: 'rock',
    id: '567ynfght7un7tuj',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Non Stop',
    soName: '(Remix)',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    duration_in_seconds: 211,
    year: '2001',
    genre: 'rock',
    id: 'e5t7e57nrthbfuytu',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Run Run',
    soName: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    duration_in_seconds: 183,
    year: '1980',
    genre: 'electronic',
    id: 'tyu67nrtbyrdyr6yb',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Eyes on Fire',
    soName: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead',
    album: 'Eyes on Fire',
    duration_in_seconds: 301,
    year: '2009',
    genre: 'hip-hop',
    id: 'nrty65756rtbdyrby656by',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Mucho Bien',
    soName: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    duration_in_seconds: 299,
    year: '2007',
    genre: 'rock',
    id: 'brst5r645br5yrdtngku',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Knives n Cherries',
    soName: '',
    author: 'minthaze',
    album: 'Captivating',
    duration_in_seconds: 84,
    year: '2009',
    genre: 'pop',
    id: 'fsrtyrby65nyntunth',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'How Deep Is Your Love',
    soName: '',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    duration_in_seconds: 33,
    year: '2012',
    genre: 'electronic',
    id: 'dfnfynut7mudtunt6d6by6yj',
  },
  {
    trackImgUrl: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    soName: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    duration_in_seconds: 500,
    year: '1999',
    genre: 'pop',
    id: 'rtbhr6e765ntdrtbnfyuny',
  },
]
