export const dataPlayList = [
  {
    id: 8,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: 'Классическая музыка',
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://skypro-music-api.skyeng.tech/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [
      {
        id: 14,
        username: 'user',
        first_name: '',
        last_name: '',
        email: 'user@mail.ru',
      },
      {
        id: 1640,
        username: 'test52',
        first_name: '',
        last_name: '',
        email: 'test52@gmail.com',
      },
    ],
  },
  {
    id: 9,
    name: 'Open Sea epic',
    author: 'Frank Schroter',
    release_date: '2019-06-12',
    genre: 'Классическая музыка',
    duration_in_seconds: 165,
    album: 'Open Sea epic',
    logo: null,
    track_file:
      'https://skypro-music-api.skyeng.tech/media/music_files/Frank_Schroter_-_Open_Sea_epic.mp3',
    stared_user: [
      {
        id: 14,
        username: 'user',
        first_name: '',
        last_name: '',
        email: 'user@mail.ru',
      },
      {
        id: 4,
        username: 'allgud',
        first_name: '',
        last_name: '',
        email: 'all@m.ru',
      },
      {
        id: 9,
        username: 'nikig',
        first_name: '',
        last_name: '',
        email: 'nikig@mail.ru',
      },
      {
        id: 47,
        username: 'wwww1',
        first_name: '',
        last_name: '',
        email: 'ww@ya.ru',
      },
      {
        id: 48,
        username: 'ee2222',
        first_name: '',
        last_name: '',
        email: 'ee@ya.ru',
      },
      {
        id: 49,
        username: 'qqqqq1',
        first_name: '',
        last_name: '',
        email: 'qq@ya.ru',
      },
      {
        id: 51,
        username: 'wwww2',
        first_name: '',
        last_name: '',
        email: 'rr@ya.ru',
      },

      {
        id: 1333,
        username: 'qaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqa@mail.ru',
        first_name: '',
        last_name: '',
        email: 'qaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqa@mail.ru',
      },
    ],
  },
  {
    id: 10,
    name: 'Sneaky Snitch',
    author: 'Kevin Macleod',
    release_date: '2022-04-16',
    genre: 'Классическая музыка',
    duration_in_seconds: 305,
    album: 'Sneaky Snitch',
    logo: null,
    track_file:
      'https://skypro-music-api.skyeng.tech/media/music_files/Kevin_Macleod_-_Sneaky_Snitch.mp3',
    stared_user: [
      {
        id: 5,
        username: 'ilush',
        first_name: '',
        last_name: '',
        email: 'as@as.com',
      },
      {
        id: 8,
        username: 'test',
        first_name: '',
        last_name: '',
        email: 'test@test.ru',
      },
      {
        id: 1628,
        username: 'ki@mail.ru',
        first_name: '',
        last_name: '',
        email: 'ki@mail.ru',
      },
    ],
  },
  {
    id: 11,
    name: 'Secret Garden',
    author: 'Mixkit',
    release_date: '1972-06-06',
    genre: 'Классическая музыка',
    duration_in_seconds: 324,
    album: 'Secret Garden',
    logo: null,
    track_file:
      'https://skypro-music-api.skyeng.tech/media/music_files/Mixkit_-_Secret_Garden.mp3',
    stared_user: [
      {
        id: 5,
        username: 'ilush',
        first_name: '',
        last_name: '',
        email: 'as@as.com',
      },
      {
        id: 37,
        username: 'mmm',
        first_name: '',
        last_name: '',
        email: 'mmm@mmm.ru',
      },

      {
        id: 1457,
        username: 'fish@ka.ru',
        first_name: '',
        last_name: '',
        email: 'fish@ka.ru',
      },
      {
        id: 1602,
        username: 'larikov.web@gmail.com',
        first_name: '',
        last_name: '',
        email: 'larikov.web@gmail.com',
      },
      {
        id: 1615,
        username: 'bababas',
        first_name: '',
        last_name: '',
        email: 'xxcxx@xxx.xx',
      },
      {
        id: 1333,
        username: 'qaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqa@mail.ru',
        first_name: '',
        last_name: '',
        email: 'qaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqaqa@mail.ru',
      },
    ],
  },
]
